package com.badlogic.gdx.tools.vulkanbindinggen.generator;

import com.badlogic.gdx.tools.vulkanbindinggen.data.VulkanCommand;
import com.badlogic.gdx.tools.vulkanbindinggen.data.VulkanParam;
import com.badlogic.gdx.tools.vulkanbindinggen.data.VulkanCommand.Level; // Ensure Level is imported

import java.util.ArrayList; // Added for String param tracking
import java.util.List;
import java.util.stream.Collectors;

public class VulkanCGenerator {

    private final String targetPackage;

    public VulkanCGenerator(String targetPackage) {
        this.targetPackage = targetPackage;
    }

    // *** NEW HELPER METHOD ***
    /** Checks if a Vulkan type is likely a string pointer. */
    private boolean isStringType(String vulkanRawType) {
        return vulkanRawType != null && (vulkanRawType.equals("char*") || vulkanRawType.equals("const char*"));
    }
    // *** END NEW HELPER ***


    public String generate(List<VulkanCommand> commands) {
        StringBuilder sb = new StringBuilder();

        // Includes (stdio.h might be needed for GetStringUTFChars NULL check feedback)
        sb.append("#include <jni.h>\n");
        sb.append("#include <stdint.h>\n");
        sb.append("#include <stdio.h>\n"); // For printf
        sb.append("#include <stdlib.h> // For NULL\n");
        sb.append("#include <vulkan/vulkan.h>\n");
        sb.append("\n");
        sb.append("// Generated by VulkanBindingGenerator\n\n");


        // JNI Function Implementations
        for (VulkanCommand cmd : commands) {
            String jniReturnType = mapJNIType(cmd.returnType);
            String jniFunctionName = generateJNIFunctionName(cmd.name);

            // JNI Function Signature
            sb.append("JNIEXPORT ").append(jniReturnType).append(" JNICALL\n");
            sb.append(jniFunctionName).append("(JNIEnv* env, jclass clazz");

            // JNI Parameters - Use mapJNIType
            for (VulkanParam p : cmd.params) {
                sb.append(", ");
                String paramJNIType = mapJNIType(p.rawType); // Determine JNI type
                // *** Add Specific Debug for Signature Generation ***
                if (cmd.name.equals("vkGetInstanceProcAddr")) {
                    System.out.println("DEBUG C Gen SIGNATURE: Cmd=" + cmd.name + ", Param=" + p.name + ", RawType=" + p.rawType + ", Mapped JNI Type=" + paramJNIType);
                }
                sb.append(mapJNIType(p.rawType)); // *** Use rawType for JNI type mapping ***
                sb.append(" ");
                sb.append(p.name);
            }
            sb.append(")\n{\n");

            // --- Function Body ---

            // 1. Handle String Parameters (Get C strings from jstring)
            List<String> jstringParamNames = new ArrayList<>();
            List<String> cStringVariableNames = new ArrayList<>();
            for (VulkanParam p : cmd.params) {
                if (mapJNIType(p.rawType).equals("jstring")) {
                    String cVar = "c_" + p.name; // Name for the const char* variable
                    jstringParamNames.add(p.name);
                    cStringVariableNames.add(cVar);
                    sb.append("    const char* ").append(cVar).append(" = (*env)->GetStringUTFChars(env, ").append(p.name).append(", NULL);\n");
                    // Add NULL check immediately after getting the string
                    sb.append("    if (").append(cVar).append(" == NULL) {\n");
                    sb.append("        printf(\"Vulkan Native Error: GetStringUTFChars failed for '").append(p.name).append("' in ").append(cmd.name).append(".\\n\");\n");
                    // Release any strings obtained *before* this one failed
                    for (int i = 0; i < cStringVariableNames.size() - 1; i++) {
                        sb.append("        (*env)->ReleaseStringUTFChars(env, ").append(jstringParamNames.get(i)).append(", ").append(cStringVariableNames.get(i)).append(");\n");
                    }
                    appendErrorReturn(sb, jniReturnType, cmd.returnType); // Generate appropriate error return (0, NULL, or nothing for void)
                    sb.append("        return").append(jniReturnType.equals("void") ? "" : " JNI_ERR").append(";\n"); // Added explicit return for safety, JNI_ERR is common convention
                    sb.append("    }\n");
                }
            }
            if (!jstringParamNames.isEmpty()) {
                sb.append("\n"); // Add separation if strings were processed
            }

            // 2. Prepare native argument list using C variables where needed
            List<String> nativeCallArgs = new ArrayList<>();
            int stringIndex = 0; // To get the correct c_... variable name
            for (VulkanParam p : cmd.params) {
                if (mapJNIType(p.rawType).equals("jstring")) {
                    nativeCallArgs.add(cStringVariableNames.get(stringIndex++)); // Use the c_... variable
                } else {
                    nativeCallArgs.add(castCParam(p.rawType, p.name)); // Cast other JNI types
                }
            }
            String joinedNativeArgs = String.join(", ", nativeCallArgs);

            // 3. Call the Vulkan function (load pointer if needed)
            boolean isGIPA = cmd.name.equals("vkGetInstanceProcAddr");
            boolean loadCallSuccess = true;
            String resultVarName = "nativeResult"; // Variable to store C result
            boolean hasReturn = !cmd.returnType.equals("void");
            String returnTypeC = cmd.returnType; // Actual C return type

            if (isGIPA) {
                // Special case: Call vkGetInstanceProcAddr directly
                sb.append("    // Call vkGetInstanceProcAddr directly\n");
                if (hasReturn) sb.append("    ").append(returnTypeC).append(" ").append(resultVarName).append(" = ");
                else sb.append("    ");
                // Use the prepared arguments, including the C string variable for pName
                sb.append("vkGetInstanceProcAddr(").append(joinedNativeArgs).append(");\n");

            } else if (cmd.level == Level.INSTANCE || cmd.level == Level.GLOBAL) {
                // Load function pointer using vkGetInstanceProcAddr then call
                String instanceParamName = findInstanceParamName(cmd);
                String pfnVar = "pfn_" + cmd.name;

                if (instanceParamName == null && !nameRequiresNullInstance(cmd.name)) {
                    sb.append("    printf(\"Vulkan Native Error: Cannot call instance-level function '").append(cmd.name).append("' without a VkInstance/VkPhysicalDevice parameter.\\n\");\n");
                    loadCallSuccess = false;
                } else {
                    String instanceLoaderArg = "NULL";
                    if (instanceParamName != null) {
                        instanceLoaderArg = castCParam(findParamRawType(cmd, instanceParamName), instanceParamName);
                    }

                    // Load pointer using vkGetInstanceProcAddr
                    sb.append("    PFN_").append(cmd.name).append(" ").append(pfnVar).append(" = (PFN_").append(cmd.name).append(")")
                            .append("vkGetInstanceProcAddr(").append(instanceLoaderArg)
                            .append(", \"").append(cmd.name).append("\");\n\n");

                    sb.append("    if (").append(pfnVar).append(" == NULL) {\n");
                    sb.append("        printf(\"Vulkan Native Error: Failed to load function pointer for %s\\n\", \"").append(cmd.name).append("\");\n");
                    loadCallSuccess = false;
                    sb.append("    } else {\n");
                    // Call via function pointer using prepared arguments
                    sb.append("        ");
                    if (hasReturn) sb.append(returnTypeC).append(" ").append(resultVarName).append(" = ");
                    sb.append(pfnVar).append("(").append(joinedNativeArgs).append(");\n");
                    sb.append("    }\n");
                }
            } else if (cmd.level == Level.DEVICE) {
                // Placeholder for device level functions
                sb.append("    // Device-level function loading via vkGetDeviceProcAddr not implemented yet.\n");
                sb.append("    printf(\"Vulkan Native Error: Device-level function '").append(cmd.name).append("' call not implemented.\\n\");\n");
                loadCallSuccess = false;
            } else {
                // Unknown level
                sb.append("    printf(\"Vulkan Native Error: Unknown command level for '").append(cmd.name).append("'.\\n\");\n");
                loadCallSuccess = false;
            }

            // 4. Release C Strings obtained from GetStringUTFChars
            if (!jstringParamNames.isEmpty()) {
                sb.append("\n    // Release allocated C strings\n");
                for (int i = 0; i < jstringParamNames.size(); i++) {
                    // No need to check c_var for NULL here, as we would have returned early if GetStringUTFChars failed
                    sb.append("    (*env)->ReleaseStringUTFChars(env, ").append(jstringParamNames.get(i)).append(", ").append(cStringVariableNames.get(i)).append(");\n");
                }
            }

            // 5. Return Result (or error default)
            if (!loadCallSuccess) {
                // If loading/calling failed, return default error value
                appendErrorReturn(sb, jniReturnType, returnTypeC);
            } else if (hasReturn) {
                // If successful and has return, cast C result to JNI type
                appendReturnStatement(sb, returnTypeC, resultVarName);
            } else {
                // If successful and void, just return
                sb.append("    return;\n");
            }

            sb.append("}\n\n"); // End JNI function
        } // End loop over commands

        return sb.toString();
    }

    // --- Helper Methods --- (Ensure these are up-to-date and correct)

    private boolean nameRequiresNullInstance(String cmdName) {
        return cmdName.equals("vkEnumerateInstanceVersion") ||
                cmdName.equals("vkEnumerateInstanceLayerProperties") ||
                cmdName.equals("vkEnumerateInstanceExtensionProperties");
    }

    private String findInstanceParamName(VulkanCommand cmd) {
        for (VulkanParam p : cmd.params) {
            if (p.rawType.equals("VkInstance") || p.rawType.equals("VkPhysicalDevice")) { // Check rawType
                return p.name;
            }
        }
        return null;
    }

    private String findParamRawType(VulkanCommand cmd, String paramName) {
        if (paramName == null) return null;
        for (VulkanParam p : cmd.params) {
            if (p.name.equals(paramName)) {
                return p.rawType;
            }
        }
        return null;
    }

    private void appendErrorReturn(StringBuilder sb, String jniReturnType, String vulkanReturnType) {
        // No code needed here if the actual return happens in the GetStringUTFChars fail block
        // or if loadCallSuccess is false path handles it. Can add default if needed.
        // Example: sb.append("    // Error occurred, returning default value.\n");
    }

    private void appendReturnStatement(StringBuilder sb, String vulkanReturnType, String resultVarName) {
        String javaType = mapJavaType(vulkanReturnType); // Map C type to Java type
        switch (javaType) {
            case "void": sb.append("    return;\n"); break; // Explicit return for void
            case "long": sb.append("    return (jlong)(uintptr_t)").append(resultVarName).append(";\n"); break;
            case "int": sb.append("    return (jint)").append(resultVarName).append(";\n"); break;
            case "float": sb.append("    return (jfloat)").append(resultVarName).append(";\n"); break;
            case "double": sb.append("    return (jdouble)").append(resultVarName).append(";\n"); break;
            case "byte": sb.append("    return (jbyte)").append(resultVarName).append(";\n"); break;
            case "short": sb.append("    return (jshort)").append(resultVarName).append(";\n"); break;
            case "boolean": sb.append("    return (jboolean)").append(resultVarName).append(";\n"); break;
            default: // Includes String, which shouldn't be returned directly from Vulkan funcs
                System.err.println("Warning: Unhandled C return cast for Vulkan type: " + vulkanReturnType + " -> defaulting to jlong");
                sb.append("    return (jlong)(uintptr_t)").append(resultVarName).append(";\n");
                break;
        }
    }


    private String generateJNIFunctionName(String methodName) {
        String mangledPackage = targetPackage.replace('.', '_');
        String mangledClass = "VulkanNative"; // Assuming fixed class name
        String mangledMethod = methodName.replace("_", "_1");
        // Further mangling might be needed for overloaded methods later
        return "Java_" + mangledPackage + "_" + mangledClass + "_" + mangledMethod;
    }

    // Maps Vulkan C type to JNI C type (jint, jlong, etc.)
    private String mapJNIType(String vulkanRawType) {
        String javaType = mapJavaType(vulkanRawType); // Determine Java type first
        switch (javaType) {
            case "void": return "void";
            case "int": return "jint";
            case "long": return "jlong";
            case "float": return "jfloat";
            case "double": return "jdouble";
            case "byte": return "jbyte";
            case "short": return "jshort";
            case "boolean": return "jboolean";
            case "String": return "jstring"; // Correct mapping
            default:
                System.err.println("Warning: Unmapped JNI type for Java type: " + javaType + " (from Vulkan: " + vulkanRawType + ") -> defaulting to jobject");
                return "jobject";
        }
    }

    // Maps Vulkan C type to Java native type (should match VulkanJavaGenerator)
    private String mapJavaType(String vulkanType) {
        if (vulkanType == null || vulkanType.isEmpty()) return "void";
        vulkanType = vulkanType.trim();

        if (vulkanType.equals("const char *") || vulkanType.equals("char *") || vulkanType.equals("char const *")) {
            return "String";
        }
        if (vulkanType.equals("void")) return "void";
        if (vulkanType.equals("float")) return "float";
        if (vulkanType.equals("double")) return "double";
        if (vulkanType.equals("char") || vulkanType.equals("int8_t") || vulkanType.equals("uint8_t")) return "byte";
        if (vulkanType.equals("int16_t") || vulkanType.equals("uint16_t")) return "short";

        if (vulkanType.equals("int") || vulkanType.equals("int32_t") || vulkanType.equals("uint32_t") ||
                vulkanType.equals("VkSampleMask") || vulkanType.equals("VkBool32") ||
                (vulkanType.startsWith("Vk") && vulkanType.endsWith("Flags") && !vulkanType.endsWith("Flags64")) ||
                (vulkanType.startsWith("Vk") && (vulkanType.contains("Enum") || vulkanType.endsWith("FlagBits")) && !vulkanType.endsWith("FlagBits64"))
        ) {
            return "int";
        }

        if (vulkanType.startsWith("PFN_") ||
                vulkanType.contains("*") || // Other pointers (ensure checked AFTER char*)
                vulkanType.startsWith("Vk") || // Handles (ensure checked AFTER specific Vk types like VkBool32 etc)
                vulkanType.equals("uint64_t") || vulkanType.equals("int64_t") ||
                vulkanType.equals("size_t") || vulkanType.equals("VkDeviceSize") ||
                vulkanType.equals("VkDeviceAddress") ||
                vulkanType.equals("VkFlags64") || vulkanType.endsWith("Flags64") ||
                vulkanType.endsWith("FlagBits64") ||
                vulkanType.equals("ANativeWindow") || vulkanType.equals("HANDLE") || vulkanType.equals("DWORD")
        ) {
            return "long";
        }

        System.err.println("Warning (mapJavaType): Unmapped Java type for Vulkan type: " + vulkanType + " -> defaulting to long");
        return "long";
    }


    // Generates the C code to cast a JNI parameter to the target Vulkan type
    private String castCParam(String vulkanRawType, String paramName) {
        if (vulkanRawType == null) return paramName;
        String jniType = mapJNIType(vulkanRawType);

        if (jniType.equals("jstring")) {
            // Strings are handled by GetStringUTFChars, not casting
            System.err.println("Internal Generator Error: castCParam called for jstring: " + paramName);
            return "NULL /* ERROR: castCParam called for jstring */"; // Return something obviously wrong
        }

        if (jniType.equals("jlong")) {
            // Use uintptr_t for pointers, handles, 64-bit integers
            return "(" + vulkanRawType + ")(uintptr_t)" + paramName;
        } else {
            // Direct cast for jint, jfloat, jbyte, jshort, jboolean
            return "(" + vulkanRawType + ")" + paramName;
        }
    }
}