package com.badlogic.gdx.tools.vulkanbindinggen.generator;

import com.badlogic.gdx.tools.vulkanbindinggen.data.VulkanCommand;
import com.badlogic.gdx.tools.vulkanbindinggen.data.VulkanParam;

import java.util.List;
import java.util.stream.Collectors;

public class VulkanJavaGenerator {

    private final String targetPackage;

    public VulkanJavaGenerator(String targetPackage) {
        this.targetPackage = targetPackage;
    }

    public String generate(List<VulkanCommand> commands) {
        System.out.println(">>>> EXECUTING LATEST VulkanJavaGenerator.generate() V3 (FOR-LOOP) - Timestamp: " + System.currentTimeMillis() + " <<<<");

        StringBuilder sb = new StringBuilder();
        sb.append("package ").append(targetPackage).append(";\n\n");
        sb.append("/**\n");
        sb.append(" * Native bindings for selected Vulkan functions.\n");
        sb.append(" * Generated by VulkanBindingGenerator.\n");
        sb.append(" * Use with libGDX jnigen.\n");
        sb.append(" */\n");
        sb.append("public final class VulkanNative {\n\n");

        // Optional: Static library loading block
        sb.append("    static {\n");
        sb.append("        // Load the native library. The name must match your build system (e.g., build.gradle jnigen)\n");
        sb.append("        // System.loadLibrary(\"vulkannative\"); // Example name\n");
        sb.append("        // Or use Gdx.app.log for libGDX integration:\n");
        sb.append("        // com.badlogic.gdx.utils.SharedLibraryLoader loader = new com.badlogic.gdx.utils.SharedLibraryLoader();\n");
        sb.append("        // loader.load(\"vulkannative\");\n");
        sb.append("        System.out.println(\"Native library should be loaded by jnigen build system or manually.\");\n");
        sb.append("    }\n\n");

        sb.append("    private VulkanNative() { /* Private constructor for utility class */ }\n\n");

        // Native Method Declarations
        for (VulkanCommand cmd : commands) {
            sb.append("    /**\n");
            sb.append("     * Native binding for Vulkan command: ").append(cmd.name).append("\n");
            for (VulkanParam p : cmd.params) {
                sb.append("     * @param ").append(p.name).append(" (").append(p.rawType).append(")\n");
            }
            sb.append("     */\n");
            sb.append("    public static native ");
            sb.append(mapJavaType(cmd.returnType)); // Map return type
            sb.append(" ").append(cmd.name).append("(");

            // *** Generate Parameters using a standard FOR loop ***
            boolean firstParam = true;
            for (VulkanParam p : cmd.params) {
                if (!firstParam) {
                    sb.append(", ");
                }
                // Log input specifically for this parameter in this context
                if (cmd.name.equals("vkGetInstanceProcAddr") && p.name.equals("pName")) {
                    System.out.println("DEBUG Java Gen FOR-LOOP: Cmd=" + cmd.name + ", Param=" + p.name + ", RawType='" + p.rawType + "'");
                }
                String javaParamType = mapJavaType(p.rawType); // Call the mapping function
                // Log output specifically for this parameter in this context
                if (cmd.name.equals("vkGetInstanceProcAddr") && p.name.equals("pName")) {
                    System.out.println("DEBUG Java Gen FOR-LOOP: Mapped Type='" + javaParamType + "'");
                }

                sb.append(javaParamType).append(" ").append(p.name); // Append the mapped type and name
                firstParam = false;
            }
            // *** End FOR loop ***

            sb.append(");\n\n");
        }

        // Class Footer
        sb.append("}\n");

        return sb.toString();
    }

    // Simple type mapping from Vulkan C types to Java native types
    private String mapJavaType(String vulkanType) {
        System.out.println("DEBUG mapJavaType: Input = '" + vulkanType + "'");

        if (vulkanType == null || vulkanType.isEmpty()) return "void";

        // Handle basic types
        if (vulkanType.equals("char*") || vulkanType.equals("const char*")) {
            return "String";
        }
        if (vulkanType.equals("void")) return "void";
        if (vulkanType.equals("float")) return "float";
        if (vulkanType.equals("double")) return "double";
        if (vulkanType.equals("char") || vulkanType.equals("int8_t") || vulkanType.equals("uint8_t")) return "byte"; // jbyte
        if (vulkanType.equals("int16_t") || vulkanType.equals("uint16_t")) return "short"; // jshort

        // Most common integers map to int (jint)
        if (vulkanType.equals("int") ||
                vulkanType.equals("int32_t") ||
                vulkanType.equals("uint32_t") ||
                vulkanType.endsWith("_t") && vulkanType.contains("Flags") || // VkFlags -> uint32_t
                vulkanType.equals("VkSampleMask") || // uint32_t
                vulkanType.equals("VkBool32")) {     // uint32_t
            return "int";
        }

        // Check for enums (assume they map to int) - needs vk.xml enum parsing to be robust
        // A simple heuristic: if it starts with Vk and ends with Enum or FlagBits or similar
        if (vulkanType.startsWith("Vk") && (vulkanType.contains("Enum") || vulkanType.contains("FlagBits"))) {
            return "int";
        }


        // Pointers, Handles, uint64_t, size_t map to long (jlong)
        // This is the core simplification for jnigen pointer handling
        if (vulkanType.startsWith("PFN_") ||
                vulkanType.contains("*") || // Any pointer type
                vulkanType.startsWith("Vk") || // All Vulkan handles (VkInstance, VkDevice, etc.)
                vulkanType.equals("uint64_t") ||
                vulkanType.equals("int64_t") ||
                vulkanType.equals("size_t") ||
                vulkanType.equals("VkDeviceSize") || // uint64_t
                vulkanType.equals("ANativeWindow") || // Treat platform handles as opaque pointers
                vulkanType.equals("HANDLE") ||
                vulkanType.equals("DWORD")) // Map common Windows types seen in platform extensions
        {
            return "long";
        }

        // Fallback for unrecognized types (might need refinement)
        System.err.println("Warning: Unmapped Java type for Vulkan type: " + vulkanType + " -> defaulting to long");
        return "long"; // Default to long for opaque types/pointers
    }
}